services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=HallOfFameDb;User Id=sa;Password=SuperSecurePassword5183;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "SuperSecurePassword5183"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"